import os, json
from dotenv import load_dotenv
from openai import OpenAI
from pptx import Presentation
from pptx.util import Pt
load_dotenv()

BASE = os.path.dirname(os.path.abspath(__file__))
client = OpenAI(
    api_key=os.environ["TOKENROUTER_API_KEY"],
    base_url=os.environ["TOKENROUTER_BASE_URL"],
    timeout=90,
)
MODEL = "moonshotai/kimi-k2.5"

DECK_SYS = """You are a strategist building a pitch deck for Nivea, based on a
competitive analysis of Dove's video ads. You are given the analysis as JSON.
Design a concise, persuasive deck. Decide how many slides are needed and what each
says. Keep bullets short (max ~12 words). Open with the insight, end with the
counter-creative recommendation. Respond with ONLY valid JSON, no markdown:
{ "deck_title": str,
  "slides": [ { "title": str, "bullets": [str], "notes": str } ] }"""

def design_deck(autopsy):
    r = client.chat.completions.create(
        model=MODEL, temperature=1,
        response_format={"type": "json_object"},
        messages=[{"role": "system", "content": DECK_SYS},
                  {"role": "user", "content": json.dumps(autopsy)}],
    )
    c = r.choices[0].message.content.strip()
    c = c.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    return json.loads(c)

def render(deck, path):
    prs = Presentation()
    s = prs.slides.add_slide(prs.slide_layouts[0])
    s.shapes.title.text = deck.get("deck_title", "Nivea vs Dove")
    if len(s.placeholders) > 1:
        s.placeholders[1].text = "Generated by Ad Autopsy"
    for slide in deck.get("slides", []):
        s = prs.slides.add_slide(prs.slide_layouts[1])
        s.shapes.title.text = slide.get("title", "")
        tf = s.placeholders[1].text_frame
        tf.clear()
        for i, b in enumerate(slide.get("bullets", [])):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = b
            p.font.size = Pt(18)
        if slide.get("notes"):
            s.notes_slide.notes_text_frame.text = slide["notes"]
    prs.save(path)
    print(f"✅ Wrote {path} ({len(deck.get('slides', []))} content slides)")

def run():
    autopsy = json.load(open(os.path.join(BASE, "cache", "autopsy.json")))
    deck = design_deck(autopsy)
    json.dump(deck, open(os.path.join(BASE, "cache", "deck.json"), "w"), indent=2)
    render(deck, os.path.join(BASE, "cache", "pitch.pptx"))

if __name__ == "__main__":
    run()